name: Update GitHub Activity

on:
  schedule:
    - cron: '*/30 * * * *'  # runs every 30 minutes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update GitHub Activity

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update README
        uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
